apiVersion: v1
kind: Service
metadata:
  name: mvsac-k8s-service
  namespace: sesac
spec:
  type: ClusterIP   # LoadBalancer → ClusterIP 로 변경
  selector:
    app: mvsac_k8s
    tier: backend
  ports:
    - protocol: TCP
      port: 80         # 클러스터 내에서 접근할 포트
      targetPort: 8000 # 컨테이너 포트 (uvicorn)